import {
  AboutUsSvg,
  ContactUsSvg,
  CoursesSvg,
  EmailMarketingSvg,
} from "@/assets/svg";

import { profile } from "@/assets/images";

const tempInstructors: Instructor[] = [
  {
    id: "123e4567-e89b-12d3-a456-426614174000",
    name: "Mary Moe",
    area: "Content Production",
    profile: CoursesSvg,
    courses: 25,
    students: 74500,
    certificates: 2591,
    averageRating: 4.0,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago",
  },
  {
    id: "716e4567-e85b-12d3-a456-426614174000",
    name: "Angela Martins",
    area: "Product Management",
    profile: profile,
    courses: 85,
    students: 87500,
    certificates: 45691,
    averageRating: 4.8,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago",
  },
  {
    id: "dm4567-e89b-12d3-a456-426614174002",
    name: "David Malan",
    area: "Computer Science",
    profile: "https://cs.harvard.edu/malan",
    courses: 10,
    students: 6200000,
    certificates: 100000,
    averageRating: 4.9,
    isFollowing: true,
    isVerified: true,
    date: "1 month ago",
  },
  {
    id: "rg4567-e89b-12d3-a456-426614174003",
    name: "React Guru",
    area: "Frontend Development",
    profile: "https://reactjsguru.com",
    courses: 50,
    students: 500000,
    certificates: 25000,
    averageRating: 4.8,
    isFollowing: true,
    isVerified: true,
    date: "2 weeks ago",
  },
  {
    id: "700db807-163c-4b54-99db-caea83cd68fb",
    name: "Esther Amadi",
    area: "product research",
    profile: "/avatars/esther-amadi.png",
    courses: 4,
    students: 2300,
    certificates: 123,
    averageRating: 4.6,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago"
  },
  {
    id: "49c01555-67c6-493b-ba7b-479bd05ac753",
    name: "Angela Martins",
    area: "frontend engineering",
    profile: "/avatars/angela-martins.png",
    courses: 5,
    students: 14400,
    certificates: 2570,
    averageRating: 4.7,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago"
  },
  {
    id: "ee666a11-588e-4718-8aac-83e2c00b4c14",
    name: "Okonkwo Mesla",
    area: "ui/ux design",
    profile: "/avatars/okonkwo-mesla.png",
    courses: 4,
    students: 2165,
    certificates: 89,
    averageRating: 3.7,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago"
  },
  {
    id: "e8d0f2c9-d6f8-48a4-923e-c699382e0a57",
    name: "Keith Mensah",
    area: "technical writing",
    profile: "/avatars/keith-mensah.png",
    courses: 4,
    students: 14300,
    certificates: 685,
    averageRating: 4.4,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago"
  },
  {
    id: "18ff0c0a-e753-4b9b-8215-eb72b18a39f9",
    name: "Lee Chong",
    area: "product marketing",
    profile: "/avatars/lee-chong.png",
    courses: 3,
    students: 1360,
    certificates: 89,
    averageRating: 3.6,
    isFollowing: true,
    isVerified: true,
    date: "3 months ago"
  },
  {
    id: "react-001",
    name: "Maximilian Schwarzmüller",
    area: "react development",
    profile: "/avatars/max-schwarz.png",
    courses: 8,
    students: 225000,
    certificates: 11200,
    averageRating: 4.8,
    isFollowing: false,
    isVerified: true,
    date: "6 months ago"
  },
  {
    id: "fcc-001",
    name: "Free CodeCamp",
    area: "fullstack development",
    profile: "/avatars/fcc-logo.png",
    courses: 20,
    students: 1200000,
    certificates: 210000,
    averageRating: 4.9,
    isFollowing: false,
    isVerified: true,
    date: "2 years ago"
  }
];

const tempCourses: Course[] = [
  {
    id: "6528fe75a49e4d8f7c1a1001",
    slug: "free-affiliate-marketing-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.7,
    reviews: 2200,
    category: "affiliate marketing",
    thumbnail: "https://img.youtube.com/vi/lSaIN0UHuZc/maxresdefault.jpg",
    title: "FREE Affiliate Marketing Course for Beginners",
    videoURL: "https://www.youtube.com/watch?v=lSaIN0UHuZc",
    instructorId: "6528fe75a49e4d8f7c1a9001",
    instructorName: "Ciaran Doyle",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLR3K1gK1gK1gK1gK1gK1gK1gK1gK1gK1gK1g=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.udemy.com/user/ciaran-doyle/",
    isVerified: true,
    isFollowing: true,
    date: "2 years ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1002",
    slug: "email-marketing-certification-hubspot",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.8,
    reviews: 3500,
    category: "email marketing",
    thumbnail: "https://img.youtube.com/vi/B8Z4LCe4BsA/maxresdefault.jpg",
    title: "Email Marketing Certification Course",
    videoURL: "https://www.youtube.com/watch?v=B8Z4LCe4BsA",
    instructorId: "6528fe75a49e4d8f7c1a9002",
    instructorName: "HubSpot Academy",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQ3K1gK1gK1gK1gK1gK1gK1gK1gK1gK1gK1g=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://academy.hubspot.com/",
    isVerified: true,
    isFollowing: true,
    date: "3 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1003",
    slug: "free-ux-design-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.6,
    reviews: 1800,
    category: "ui/ux design",
    thumbnail: "https://img.youtube.com/vi/1hHMwLxN6EM/maxresdefault.jpg",
    title: "Introduction to UX Design",
    videoURL: "https://www.youtube.com/watch?v=1hHMwLxN6EM",
    instructorId: "6528fe75a49e4d8f7c1a9003",
    instructorName: "UX Design Institute",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLR3K1gK1gK1gK1gK1gK1gK1gK1gK1gK1gK1g=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.uxdesigninstitute.com/",
    isVerified: true,
    isFollowing: true,
    date: "1 year ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1004",
    slug: "content-marketing-certification-hubspot",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.9,
    reviews: 4000,
    category: "content creation",
    thumbnail: "https://img.youtube.com/vi/3b0cYpE9bds/maxresdefault.jpg",
    title: "Content Marketing Certification Course",
    videoURL: "https://www.youtube.com/watch?v=3b0cYpE9bds",
    instructorId: "6528fe75a49e4d8f7c1a9004",
    instructorName: "HubSpot Academy",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQ3K1gK1gK1gK1gK1gK1gK1gK1gK1gK1gK1g=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://academy.hubspot.com/",
    isVerified: true,
    isFollowing: true,
    date: "6 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1005",
    slug: "graphic-design-basics",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.5,
    reviews: 2700,
    category: "graphic design",
    thumbnail: "https://img.youtube.com/vi/1l0aE2pHkz0/maxresdefault.jpg",
    title: "Graphic Design Basics: Core Principles for Visual Design",
    videoURL: "https://www.youtube.com/watch?v=1l0aE2pHkz0",
    instructorId: "6528fe75a49e4d8f7c1a9005",
    instructorName: "Canva",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLR3K1gK1gK1gK1gK1gK1gK1gK1gK1gK1gK1g=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.canva.com/learn/",
    isVerified: true,
    isFollowing: true,
    date: "10 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1006",
    slug: "introduction-to-computer-science",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.8,
    reviews: 12000,
    category: "computer science",
    thumbnail: "https://img.youtube.com/vi/8mAITcNt710/maxresdefault.jpg",
    title: "Introduction to Computer Science - Harvard's CS50",
    videoURL: "https://www.youtube.com/watch?v=8mAITcNt710",
    instructorId: "6528fe75a49e4d8f7c1a9001",
    instructorName: "David J Malan",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://cs50.harvard.edu",
    isVerified: true,
    isFollowing: true,
    date: "2 years ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1007",
    slug: "python-for-everybody",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.7,
    reviews: 9500,
    category: "programming",
    thumbnail: "https://img.youtube.com/vi/8DvywoWv6fI/maxresdefault.jpg",
    title: "Python for Everybody - University of Michigan",
    videoURL: "https://www.youtube.com/watch?v=8DvywoWv6fI",
    instructorId: "6528fe75a49e4d8f7c1a9002",
    instructorName: "Charles Severance",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.dr-chuck.com",
    isVerified: true,
    isFollowing: true,
    date: "3 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1008",
    slug: "machine-learning-stanford",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.9,
    reviews: 15000,
    category: "data science",
    thumbnail: "https://img.youtube.com/vi/GwIo3gDZCVQ/maxresdefault.jpg",
    title: "Machine Learning - Stanford University",
    videoURL: "https://www.youtube.com/watch?v=GwIo3gDZCVQ",
    instructorId: "6528fe75a49e4d8f7c1a9003",
    instructorName: "Andrew Ng",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.andrewng.org",
    isVerified: true,
    isFollowing: true,
    date: "1 year ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1009",
    slug: "introduction-to-philosophy",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.6,
    reviews: 8000,
    category: "philosophy",
    thumbnail: "https://img.youtube.com/vi/1A_CAkYt3GY/maxresdefault.jpg",
    title: "Introduction to Philosophy - MIT OpenCourseWare",
    videoURL: "https://www.youtube.com/watch?v=1A_CAkYt3GY",
    instructorId: "6528fe75a49e4d8f7c1a9004",
    instructorName: "Caspar Hare",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://ocw.mit.edu",
    isVerified: true,
    isFollowing: true,
    date: "6 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1010",
    slug: "the-science-of-well-being",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.9,
    reviews: 20000,
    category: "psychology",
    thumbnail: "https://img.youtube.com/vi/92tuvHkzY7k/maxresdefault.jpg",
    title: "The Science of Well-Being - Yale University",
    videoURL: "https://www.youtube.com/watch?v=92tuvHkzY7k",
    instructorId: "6528fe75a49e4d8f7c1a9005",
    instructorName: "Laurie Santos",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://psychology.yale.edu",
    isVerified: true,
    isFollowing: true,
    date: "10 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1011",
    slug: "financial-markets-yale",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.8,
    reviews: 11000,
    category: "finance",
    thumbnail: "https://img.youtube.com/vi/3z0d1gZz0x8/maxresdefault.jpg",
    title: "Financial Markets - Yale University",
    videoURL: "https://www.youtube.com/watch?v=3z0d1gZz0x8",
    instructorId: "6528fe75a49e4d8f7c1a9006",
    instructorName: "Robert Shiller",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://som.yale.edu",
    isVerified: true,
    isFollowing: true,
    date: "4 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1012",
    slug: "free-affiliate-marketing-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.5,
    reviews: 254,
    category: "affiliate marketing",
    thumbnail: "https://img.youtube.com/vi/lSaIN0UHuZc/hqdefault.jpg",
    title: "FREE Affiliate Marketing Course for Beginners",
    videoURL: "https://www.youtube.com/watch?v=lSaIN0UHuZc",
    instructorId: "6528fe75a49e4d8f7c1a9001",
    instructorName: "Ciaran Doyle",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.udemy.com/user/ciaran-doyle/",
    isVerified: true,
    isFollowing: true,
    date: "2 years ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1013",
    slug: "email-marketing-certification-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.7,
    reviews: 5000,
    category: "email marketing",
    thumbnail: "https://img.youtube.com/vi/B8Z4LCe4BsA/hqdefault.jpg",
    title: "Email Marketing FULL COURSE",
    videoURL: "https://www.youtube.com/watch?v=B8Z4LCe4BsA",
    instructorId: "6528fe75a49e4d8f7c1a9002",
    instructorName: "Klaviyo",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.klaviyo.com/",
    isVerified: true,
    isFollowing: true,
    date: "3 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1014",
    slug: "free-ux-design-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.8,
    reviews: 3200,
    category: "ui/ux design",
    thumbnail: "https://img.youtube.com/vi/2Yt6raj-S1M/hqdefault.jpg",
    title: "Introduction to UX Design",
    videoURL: "https://www.youtube.com/watch?v=2Yt6raj-S1M",
    instructorId: "6528fe75a49e4d8f7c1a9003",
    instructorName: "UX Design Institute",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.uxdesigninstitute.com/",
    isVerified: true,
    isFollowing: true,
    date: "1 year ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1015",
    slug: "content-marketing-certification",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.6,
    reviews: 4500,
    category: "content creation",
    thumbnail: "https://img.youtube.com/vi/3b0c3k3eLhI/hqdefault.jpg",
    title: "Content Marketing Certification Course",
    videoURL: "https://www.youtube.com/watch?v=3b0c3k3eLhI",
    instructorId: "6528fe75a49e4d8f7c1a9004",
    instructorName: "HubSpot Academy",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://academy.hubspot.com/",
    isVerified: true,
    isFollowing: true,
    date: "6 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1016",
    slug: "introduction-to-ui-ux-design",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.4,
    reviews: 2800,
    category: "ui/ux design",
    thumbnail: "https://img.youtube.com/vi/9B1nM3iY3xg/hqdefault.jpg",
    title: "Introduction to UI/UX Design",
    videoURL: "https://www.youtube.com/watch?v=9B1nM3iY3xg",
    instructorId: "6528fe75a49e4d8f7c1a9005",
    instructorName: "Alison",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://alison.com/",
    isVerified: true,
    isFollowing: true,
    date: "10 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1017",
    slug: "basics-of-technical-writing",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.5,
    reviews: 3100,
    category: "technical writing",
    thumbnail: "https://img.youtube.com/vi/1WvN3vZ6j6M/hqdefault.jpg",
    title: "Basics of Technical Writing",
    videoURL: "https://www.youtube.com/watch?v=1WvN3vZ6j6M",
    instructorId: "6528fe75a49e4d8f7c1a9006",
    instructorName: "Alison",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://alison.com/",
    isVerified: true,
    isFollowing: true,
    date: "4 months ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1018",
    slug: "react-for-beginners",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.7,
    reviews: 120000,
    category: "programming",
    thumbnail: "https://img.youtube.com/vi/bMknfKXIFA8/maxresdefault.jpg",
    title: "React JS Full Course - freeCodeCamp",
    videoURL: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    instructorId: "6528fe75a49e4d8f7c1a9002",
    instructorName: "Free CodeCamp",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQGx1K8g3Xjv3Z5U1z9Q3z5U1z9Q3z5U1z9Q3z5=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.youtube.com/c/Freecodecamp",
    isVerified: true,
    isFollowing: true,
    date: "1 year ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1019",
    slug: "python-data-science-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.9,
    reviews: 200000,
    category: "data science",
    thumbnail: "https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg",
    title: "Python for Data Science - freeCodeCamp",
    videoURL: "https://www.youtube.com/watch?v=rfscVS0vtbw",
    instructorId: "6528fe75a49e4d8f7c1a9003",
    instructorName: "Free CodeCamp",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQGx1K8g3Xjv3Z5U1z9Q3z5U1z9Q3z5U1z9Q3z5=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.youtube.com/c/Freecodecamp",
    isVerified: true,
    isFollowing: true,
    date: "3 years ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1020",
    slug: "git-and-github-course",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.6,
    reviews: 80000,
    category: "version control",
    thumbnail: "https://img.youtube.com/vi/RGOj5yH7evk/maxresdefault.jpg",
    title: "Git and GitHub for Beginners - freeCodeCamp",
    videoURL: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    instructorId: "6528fe75a49e4d8f7c1a9004",
    instructorName: "Free CodeCamp",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQGx1K8g3Xjv3Z5U1z9Q3z5U1z9Q3z5U1z9Q3z5=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.youtube.com/c/Freecodecamp",
    isVerified: true,
    isFollowing: true,
    date: "2 years ago",
  },
  {
    id: "6528fe75a49e4d8f7c1a1021",
    slug: "web-developer-bootcamp",
    type: "free",
    price: 0,
    oldPrice: 0,
    rating: 4.8,
    reviews: 250000,
    category: "web development",
    thumbnail: "https://img.youtube.com/vi/pKd0Rpw7O48/maxresdefault.jpg",
    title: "The Web Developer Bootcamp - freeCodeCamp",
    videoURL: "https://www.youtube.com/watch?v=pKd0Rpw7O48",
    instructorId: "6528fe75a49e4d8f7c1a9005",
    instructorName: "Free CodeCamp",
    instructorProfileImage: "https://yt3.ggpht.com/ytc/AKedOLQGx1K8g3Xjv3Z5U1z9Q3z5U1z9Q3z5U1z9Q3z5=s88-c-k-c0x00ffffff-no-rj",
    instructorProfileURL: "https://www.youtube.com/c/Freecodecamp",
    isVerified: true,
    isFollowing: true,
    date: "1 year ago",
  },
];

const tempBlogs: Blog[] = [
  {
    id: "123e4567-e89b-12d3-a456-426614174000",
    category: "Technology",
    thumbnail: ContactUsSvg,
    title: "The Future of Web Development",
    body: "In this blog post, we will explore the latest trends and technologies shaping the future of web development...",
    posterName: "John Doe",
    posterProfileImage: CoursesSvg,
    posterProfileURL: "https://www.example.com/johndoe",
    isVerified: false,
    isFollowing: true,
    isLiked: true,
    likes: 120,
    comments: {
      count: 25,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 8790,
    date: "1 year ago",
  },
  {
    id: "789a0123-4567-89ab-cdef-123456789000",
    category: "Travel",
    thumbnail: CoursesSvg,
    title: "Exploring the Hidden Gems of Italy",
    body: "Italy is known for its iconic landmarks, but there are also many hidden gems waiting to be discovered...",
    posterName: "Jane Smith",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/janesmith",
    isLiked: false,
    likes: 87,
    isVerified: false,
    isFollowing: false,
    comments: {
      count: 14,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni dolorem, dicta maiores vel sequi adipisci necessitatibus hic iure quibusdam facilis sint harum corporis minima itaque ad assumenda sed cumque numquam optio? Qui quisquam eveniet quod quis quasi veniam magnam rem nemo. Quos unde illum laborum architecto optio reiciendis possimus expedita!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni dolorem, dicta maiores vel sequi adipisci necessitatibus hic iure quibusdam facilis sint harum corporis minima itaque ad assumenda sed cumque numquam optio? Qui quisquam eveniet quod quis quasi veniam magnam rem nemo. Quos unde illum laborum architecto optio reiciendis possimus expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni dolorem, dicta maiores vel sequi adipisci necessitatibus hic iure quibusdam facilis sint harum corporis minima itaque ad assumenda sed cumque numquam optio? Qui quisquam eveniet quod quis quasi veniam magnam rem nemo. Quos unde illum laborum architecto optio reiciendis possimus expedita!",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "king mane",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 90,
    date: "6 months ago",
  },
  {
    id: "fedcba09-8765-4321-abcd-efghijklmnop",
    category: "Food",
    thumbnail: CoursesSvg,
    title: "The Best Vegan Recipes for Beginners",
    body: "Going vegan doesn't have to be difficult! This blog post features delicious and easy vegan recipes...",
    posterName: "Sarah Lee",
    posterProfileImage: profile,
    posterProfileURL: "https://www.example.com/sarahlee",
    isVerified: true,
    isFollowing: true,
    isLiked: false,
    likes: 152,
    comments: {
      count: 38,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: false,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 189,
    date: "3 months ago",
  },
  {
    id: "01234567-89ab-cdef-fedc-ba0987654321",
    category: "Lifestyle",
    thumbnail: AboutUsSvg,
    title: "Building a Minimacollection Wardrobe",
    body: "Decluttering your closet can be a liberating experience. Learn tips on creating a minimacollection wardrobe...",
    posterName: "Michael Chen",
    posterProfileImage: EmailMarketingSvg,
    posterProfileURL: "https://www.example.com/michaelchen",
    isVerified: true,
    isFollowing: false,
    isLiked: true,
    likes: 98,
    comments: {
      count: 19,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 678,
    date: "8 months ago",
  },
  {
    id: "cbacdef0-1234-5678-9abc-fedcba098765",
    category: "Business",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "The Power of Effective Communication in the Workplace",
    body: "Communication is key to success in any business. This blog post explores strategies for effective communication...",
    posterName: "David Miller",
    posterProfileImage: AboutUsSvg,
    posterProfileURL: "https://www.example.com/davidmiller",
    isVerified: true,
    isFollowing: true,
    isLiked: false,
    likes: 115,
    comments: {
      count: 27,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 218,
    date: "4 months ago",
  },
  {
    id: "fec0ba98-7654-3210-fedc-ba0987654321",
    category: "Photography",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "Capturing Stunning Landscapes: Photography Tips for Beginners",
    body: "The world is full of breathtaking landscapes waiting to be captured. This blog post provides tips for beginners...",
    posterName: "Sarah Lee",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/sarahlee",
    isVerified: true,
    isFollowing: false,
    isLiked: true,
    likes: 178,
    comments: {
      count: 42,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 654,
    date: "2 years ago",
  },
  {
    id: "98765432-0123-4567-89ab-cdef01234567",
    category: "Health & Fitness",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "Developing a Sustainable Exercise Routine",
    body: "Exercise is essential for a healthy lifestyle, but consistency is key. Learn tips for building a sustainable routine...",
    posterName: "Emily Jones",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/emilyjones",
    isVerified: true,
    isFollowing: true,
    isLiked: false,
    likes: 132,
    comments: {
      count: 31,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 2158,
    date: "9 months ago",
  },
  {
    id: "21098765-4321-0fed-cba9-876543210123",
    category: "Music",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "The History of Jazz Music: From Its Roots to Modern Day",
    body: "Jazz music is a rich and vibrant genre with a long history. This blog post explores the evolution of jazz...",
    posterName: "William Brown",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/williambrown",
    isVerified: true,
    isFollowing: true,
    isLiked: true,
    likes: 85,
    comments: {
      count: 17,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 4163,
    date: "7 months ago",
  },
  {
    id: "3210fedc-ba98-7654-3210-fedcba098765",
    category: "Entertainment",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "The Best Board Games for Family Game Night",
    body: "Board games are a fantastic way to connect with family and friends. This blog post recommends some of the best board games...",
    posterName: "Olivia Rodriguez",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/oliviarodriguez",
    isVerified: true,
    isFollowing: true,
    isLiked: false,
    likes: 101,
    comments: {
      count: 24,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 4890,
    date: "5 months ago",
  },
  {
    id: "43210987-6543-210f-edc0-ba9876543210",
    category: "Science",
    thumbnail: "https://via.placeholder.com/150x150",
    title: "The Wonders of the Natural World: Exploring Biodiversity",
    body: "Our planet is teeming with diverse life forms. This blog post explores the concept of biodiversity...",
    posterName: "Christopher Lee",
    posterProfileImage: "https://via.placeholder.com/100x100",
    posterProfileURL: "https://www.example.com/christopherlee",
    isVerified: true,
    isFollowing: false,
    isLiked: true,
    likes: 147,
    comments: {
      count: 35,
      comments: [
        {
          id: "13245-tu672-91890-u1h721gew7",
          comment: "This is a very nice course",
          isLiked: true,
          commenter: {
            id: "178gbd3-4094nyu-teb53b3",
            username: "marvis travail",
            profile: profile,
            isVerified: true,
          },
          likes: 7,
          date: "7 hours ago",
          replies: {
            count: 4,
            replies: [
              {
                id: "158793-ifujuds-6784-euyvw",
                reply: "Thanks, hope you enjoyed it",
                commentId: "13415-gt83rghwriuoes-574289",
                isLiked: true,
                likes: 400,
                date: "8 minutes ago",
                replier: {
                  id: "31267fdgvx-71tsyewew-7239b1",
                  username: "Rick Tochukwu",
                  profile: AboutUsSvg,
                  isVerified: true,
                },
                replyTo: {
                  id: "13245-tu672-91890-u1h721gew7",
                  username: "marvis travail",
                  profile: profile,
                },
              },
            ],
          },
        },
      ],
    },
    views: 790,
    date: "10 months ago",
  },
];

const tempClips: Clip[] = [
  
  {
    id: "clip-001",
    title: "What is Affiliate Marketing?",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 60,
    instructorName: "John Doe",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/johndoe",
    progress: 20,
    rating: 4.2,
    userRating: 3.5,
    isVerified: true,
    isFollowing: false,
    isFavorite: false,
    collection: ["marketing", "money", "digital"],
    date: "2 weeks ago",
  },
  {
    id: "clip-002",
    title: "Best Tools for Writers in 2024",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 90,
    instructorName: "Micheal Canvas",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/michael-canvas",
    progress: 5,
    rating: 4.6,
    userRating: 4.0,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: ["writing", "tools"],
    date: "4 days ago",
  },
  {
    id: "clip-003",
    title: "JavaScript Event Loop Explained",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 75,
    instructorName: "Sarah Flux",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/sarah-flux",
    progress: 80,
    rating: 4.8,
    userRating: 4.5,
    isVerified: true,
    isFollowing: true,
    isFavorite: true,
    collection: ["javascript", "frontend", "dev"],
    date: "1 month ago",
  },
  {
    id: "clip-004",
    title: "3 Ways to Monetize a Blog",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 45,
    instructorName: "Liam Codes",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/liam-codes",
    progress: 10,
    rating: 4.0,
    userRating: 3.8,
    isVerified: false,
    isFollowing: false,
    isFavorite: false,
    collection: ["blog", "monetization", "seo"],
    date: "6 days ago",
  },
  {
    id: "clip-005",
    title: "What’s New in React 19",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 50,
    instructorName: "React Guru",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/react-guru",
    progress: 100,
    rating: 4.9,
    userRating: 5.0,
    isVerified: true,
    isFollowing: true,
    isFavorite: true,
    collection: ["react", "frontend", "dev"],
    date: "1 day ago",
  },
  {
    id: "clip-006",
    title: "5 Tips for Better UI Design",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 70,
    instructorName: "Design Queen",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/design-queen",
    progress: 40,
    rating: 4.7,
    userRating: 4.2,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: ["ui", "ux", "design"],
    date: "3 weeks ago",
  },
  {
    id: "clip-007",
    title: "How Hackers Exploit Public Wi-Fi",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 80,
    instructorName: "CyberKnight",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/cyberknight",
    progress: 60,
    rating: 4.5,
    userRating: 4.3,
    isVerified: true,
    isFollowing: false,
    isFavorite: true,
    collection: ["security", "wifi", "hacking"],
    date: "5 days ago",
  },
  {
    id: "clip-008",
    title: "AI & You: Tools That Make You Smarter",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 65,
    instructorName: "Dr. Ada Byte",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/ada-byte",
    progress: 35,
    rating: 4.8,
    userRating: 4.6,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: ["ai", "productivity", "tools"],
    date: "1 week ago",
  },
  {
    id: "clip-009",
    title: "API Security for Backend Developers",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 95,
    instructorName: "Node Ninja",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/node-ninja",
    progress: 15,
    rating: 4.3,
    userRating: 4.0,
    isVerified: true,
    isFollowing: false,
    isFavorite: false,
    collection: ["backend", "api", "security"],
    date: "3 days ago",
  },
  {
    id: "clip-010",
    title: "Building Mobile Apps with Flutter",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    thumbnail: "https://placehold.co/300x500",
    duration: 100,
    instructorName: "Flutter King",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://example.com/flutter-king",
    progress: 0,
    rating: 4.6,
    userRating: 0.0,
    isVerified: true,
    isFollowing: false,
    isFavorite: false,
    collection: ["flutter", "mobile", "crossplatform"],
    date: "12 hours ago",
  },
];

const tempPurchasedCourses: PurchasedCourse[] = [
  {
    id: "123e4567-e89b-12d3-a456-426614174000",
    subject: "affiliate marketing",
    thumbnail: CoursesSvg,
    title: "The Ultimate JavaScript Course",
    progress: 40,
    instructorName: "John Doe",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/johndoe",
    rating: 4.4,
    userRating: 3.5,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: [],
    date: "2 years ago",
  },
  {
    id: "153e4867-e79b-45d3-a456-426614178900",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "Technical Writing: From amature to advanced",
    progress: 10,
    instructorName: "Micheal Canvas",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/michael-canvas",
    rating: 4.4,
    userRating: 3.5,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: ["writing"],
    date: "7 months ago",
  },
  {
    id: "148e4967-e99b-12d3-a706-425814174000",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "content creation: how to create contents like a pro",
    progress: 80,
    instructorName: "Brain Jotter",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/brain-jotter",
    rating: 5,
    userRating: 4,
    isVerified: true,
    isFollowing: false,
    isFavorite: true,
    collection: ["content creation", "extra courses"],
    date: "7 months ago",
  },
  {
    id: "323e4867-e79b-12d3-a456-426614174567",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "Technical Writing: From amature to advanced",
    progress: 10,
    instructorName: "Micheal Canvas",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/michael-canvas",
    rating: 4.4,
    userRating: 3.5,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: ["writing", "watched"],
    date: "7 months ago",
  },
  {
    id: "263e4867-e99b-11d3-a706-528814374800",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "content creation: how to create contents like a pro",
    progress: 80,
    instructorName: "Brain Jotter",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/brain-jotter",
    rating: 5,
    userRating: 4,
    isVerified: true,
    isFollowing: false,
    isFavorite: true,
    collection: ["content creation"],
    date: "7 months ago",
  },
  {
    id: "353e4867-e02b-12d3-a456-426614174900",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "Technical Writing: From amature to advanced",
    progress: 10,
    instructorName: "Micheal Canvas",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/michael-canvas",
    rating: 4.4,
    userRating: 3.5,
    isVerified: true,
    isFollowing: true,
    isFavorite: false,
    collection: [],
    date: "7 months ago",
  },
  {
    id: "263e4867-e99b-12d3-a706-425814174000",
    subject: "technical writing",
    thumbnail: AboutUsSvg,
    title: "content creation: how to create contents like a pro",
    progress: 80,
    instructorName: "Brain Jotter",
    instructorProfileImage: "https://via.placeholder.com/100x100",
    instructorProfileURL: "https://www.example.com/brain-jotter",
    rating: 5,
    userRating: 4,
    isVerified: true,
    isFollowing: false,
    isFavorite: true,
    collection: [],
    date: "7 months ago",
  },
];

export { tempCourses, tempBlogs, tempPurchasedCourses, tempInstructors, tempClips };
